[package]
name = "krampus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.6"
image = "0.24.7"
term_size = "1.0.0-beta.2"
